- hosts: 192.168.43.148
  vars_prompt:
  - name: dvd_dir
    prompt: "Enter dvd mount point: "
    private: no

  - name: httpd_port
    prompt: "Enter port number for httpd: "
    private: no

  - name: doc_root
    prompt: "Enter document root for httpd: "
    private: no

  tasks:
  - file: 
     state: directory
     path: "/{{dvd_dir}}"

  - mount:
     src: "/dev/cdrom"
     path: "/{{dvd_dir}}"
     fstype: "iso9660"
     state: mounted
 
  - yum_repository:
     baseurl: "/{{dvd_dir}}/AppStream"
     gpgcheck: 0
     name: "App_dvd"
     description: "AppStream repo"
  
  - yum_repository:
     baseurl: "/{{dvd_dir}}/BaseOS"
     gpgcheck: 0
     name: "Base_dvd"
     description: "BaseOS repo"

  - package:
     state: present
     name: "httpd"

  - file:
     state: directory
     path: "{{doc_root}}"
          
  - template:
     dest: "/etc/httpd/conf.d/lw.conf"
     src: "my_httpd.conf"
    notify:
    - Restart httpd 
 
  - copy: 
     dest : "{{doc_root}}/index.html"
     content: "this is web file by the ansible\n"

  - firewalld:
     state: enabled
     port: "{{httpd_port}}/tcp"
     permanent: yes
     immediate: yes


  handlers:
  - name: Restart httpd
    service:
     name: "httpd"
     state: started
     enabled: yes
